# EntityManager Configuration v5.4
# Blocked items require permission to override 
# Do NOT change Config_Revision unless you want unexpected errors!
# Potion blocking - 'Potion:(potionid)' - Can block from dispensers and usage
# Entity blocking - 'Zombie:baby:villager' - Blocks baby zombie villagers. 'Zombie:villager' - Blocks zombie villagers 'Zombie:baby' - blocks baby zombies 'sheep:baby:green' - Blocks green baby sheep 'sheep:green' - Blocks all green sheep
Settings:
  Config_Revision: 1.4
  Admin-Alerts: true
  Player-Alerts: true
  Logging: true
Disable:
  Weather:
    Rain: false
    Thunder: false
    Lightning: false
  Interaction:
    PVP: false
    Fishing: false 
    Shooting: false
    Enchanting: false
    Fireworks: false
    Trading: false
    Portal_Creation: false
  Usage:
    Blocked_Items:
    - Exp_Bottle
    - Fireball
    - Potion:16394
  Dispensing:
    Blocked_Items:
    - Bedrock
    - Diamond_Block
  Other:
    Monster_Spawner_Exp: false
    Monster_Spawner_Drops: false
TimeManager:
  Enabled: false
  Target_Time: 12000
  Set_Every: 100
EggManager:
  Disabled_Eggs:
  - ghast
SpawnManager:
  Remove_Armor: false
  Disallowed_Mobs:
  - silverfish
  - zombie:baby:villager
  Disallowed_Reasons:
  - lightning
DeathManager:
  Player:
    Keep_Exp: false
    Keep_Items: false
  Entity:
    Drop_Exp: true
    Drop_Items: true